config/routes.rb
MVP::Application.routes.draw do

  root :to => "home#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "follow/index"

  get "follow/new"

  match "home" => "signups#new"
  match "/meow" => "home#meow"
  get "/done" => "signups#done"
  get "/thanks" => "signups#thanks"
  match "/hosts" => "profiles#index"

  get "home/index"
  get "home/howitworks"
  get "home/teamandjobs"
  get "home/tos"
  get "home/philosophy"
  get "home/unsubscribe"
  get "home/privacy"
  get "home/raffle"

  resources :images
  resources :signups
  resources :guests
  resources :comments
  resources :locations

  namespace :api do
    resources :charges
    resources :campaigns
    resources :events
    resources :locations
    resources :profiles
    resources :follows
    resources :guests
    get "/referral_code_check" => "charges#referral_code_check"
  end

  resources :campaigns
  resources :profiles

  match 'my_profile' => 'profiles#show'
  match 'edit_my_profile' => 'profiles#edit'

  resources :events do
    resources :tickets do
      resources :guests
    end
    resources :images
    resources :follows
  end

  devise_for :users, controllers: {omniauth_callbacks: "authentications"} do
  ActiveAdmin.routes(self)
    resource :image
  end

  resources :user_answers
  resources :survey_questions
  
  resources :points
  
  get "survey" => "survey_questions#survey"
  match "/turtletower" => redirect("https://www.surveymonkey.com/s/LT7SDWX"), :as => :turtletower
  match "/ejis" => redirect("https://www.surveymonkey.com/s/JFCRCPX"), :as => :eji
  match "/wine" => redirect("https://www.surveymonkey.com/s/M28VBR3"), :as => :wine
  match "/beans" => redirect("https://www.surveymonkey.com/s/M22C8BQ"), :as => :beans
  match "/riceball" => redirect("https://www.surveymonkey.com/s/3HBGRCT"), :as=> :riceball
  match "/meatballs" => redirect("https://www.surveymonkey.com/s/QLJVVKV"), :as=> :meatballs
  match "/rak" => redirect("https://www.surveymonkey.com/s/GJZFJ2S"), :as => :rak
  match "/antologia" => redirect("/events/14")
  match "/capos" => redirect("/events/20")
  match "/radioafrica" => redirect("/events/24")
  match "/contraband" => redirect("/events/29")
  match "/onigilly" => redirect("/events/26")
  match "/HSC" => redirect("/events/30")
  match "/hsc" => redirect("/events/30")
  

  match 'events/:id/post_event' => 'events#post_event'

end

app/models/user_answer.rb
# == Schema Information
#
# Table name: user_answers
#
#  id                 :integer          not null, primary key
#  user_id            :integer
#  survey_question_id :integer
#  text               :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class UserAnswer < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :survey_question
  
  attr_accessible :survey_question_id, :text, :user_id
end

app/controllers/user_answers_controller.rb
class UserAnswersController < ApplicationController
  # GET /user_answers
  # GET /user_answers.json
  def index
    @user_answers = UserAnswer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_answers }
    end
  end

  # GET /user_answers/1
  # GET /user_answers/1.json
  def show
    @user_answer = UserAnswer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_answer }
    end
  end

  # GET /user_answers/new
  # GET /user_answers/new.json
  def new
    @user_answer = UserAnswer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_answer }
    end
  end

  # GET /user_answers/1/edit
  def edit
    @user_answer = UserAnswer.find(params[:id])
  end

  # POST /user_answers
  # POST /user_answers.json
  def create
    @answers = params[:user_answers]
    @answers.each do |key, value|
      UserAnswer.create(:user_id => current_user.id, :survey_question_id => key.to_i, :text => value)
    end
    redirect_to :root
  end

  # PUT /user_answers/1
  # PUT /user_answers/1.json
  def update
    @user_answer = UserAnswer.find(params[:id])

    respond_to do |format|
      if @user_answer.update_attributes(params[:user_answer])
        format.html { redirect_to @user_answer, notice: 'User answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_answers/1
  # DELETE /user_answers/1.json
  def destroy
    @user_answer = UserAnswer.find(params[:id])
    @user_answer.destroy

    respond_to do |format|
      format.html { redirect_to user_answers_url }
      format.json { head :no_content }
    end
  end
end

app/views/user_answers/_form.html.haml
= form_for @user_answer do |f|
  - if @user_answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user_answer.errors.count, "error")} prohibited this user_answer from being saved:"
      %ul
        - @user_answer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :survey_question_id
    = f.number_field :survey_question_id
  .field
    = f.label :text
    = f.text_area :text
  .actions
    = f.submit 'Save'

app/views/user_answers/edit.html.haml
%h1 Editing user_answer

= render 'form'

= link_to 'Show', @user_answer
\|
= link_to 'Back', user_answers_path

app/views/user_answers/index.html.haml
%h1 Listing user_answers

%table
  %tr
    %th User
    %th Survey question
    %th Text
    %th
    %th
    %th

  - @user_answers.each do |user_answer|
    %tr
      %td= user_answer.user_id
      %td= user_answer.survey_question_id
      %td= user_answer.text
      %td= link_to 'Show', user_answer
      %td= link_to 'Edit', edit_user_answer_path(user_answer)
      %td= link_to 'Destroy', user_answer, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User answer', new_user_answer_path

app/views/user_answers/new.html.haml
%h1 New user_answer

= render 'form'

= link_to 'Back', user_answers_path

app/views/user_answers/show.html.haml
%p#notice= notice

%p
  %b User:
  = @user_answer.user_id
%p
  %b Survey question:
  = @user_answer.survey_question_id
%p
  %b Text:
  = @user_answer.text

= link_to 'Edit', edit_user_answer_path(@user_answer)
\|
= link_to 'Back', user_answers_path