config/routes.rb
MVP::Application.routes.draw do

  root :to => "home#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "follow/index"

  get "follow/new"

  match "home" => "signups#new"
  match "/meow" => "home#meow"
  get "/done" => "signups#done"
  get "/thanks" => "signups#thanks"
  match "/hosts" => "profiles#index"

  get "home/index"
  get "home/howitworks"
  get "home/teamandjobs"
  get "home/tos"
  get "home/philosophy"
  get "home/unsubscribe"
  get "home/privacy"
  get "home/raffle"

  resources :images
  resources :signups
  resources :guests
  resources :comments
  resources :locations

  namespace :api do
    resources :charges
    resources :campaigns
    resources :events
    resources :locations
    resources :profiles
    resources :follows
    resources :guests
    get "/referral_code_check" => "charges#referral_code_check"
  end

  resources :campaigns
  resources :profiles

  match 'my_profile' => 'profiles#show'
  match 'edit_my_profile' => 'profiles#edit'

  resources :events do
    resources :tickets do
      resources :guests
    end
    resources :images
    resources :follows
  end

  devise_for :users, controllers: {omniauth_callbacks: "authentications"} do
  ActiveAdmin.routes(self)
    resource :image
  end

  resources :user_answers
  resources :survey_questions
  
  resources :points
  
  get "survey" => "survey_questions#survey"
  match "/turtletower" => redirect("https://www.surveymonkey.com/s/LT7SDWX"), :as => :turtletower
  match "/ejis" => redirect("https://www.surveymonkey.com/s/JFCRCPX"), :as => :eji
  match "/wine" => redirect("https://www.surveymonkey.com/s/M28VBR3"), :as => :wine
  match "/beans" => redirect("https://www.surveymonkey.com/s/M22C8BQ"), :as => :beans
  match "/riceball" => redirect("https://www.surveymonkey.com/s/3HBGRCT"), :as=> :riceball
  match "/meatballs" => redirect("https://www.surveymonkey.com/s/QLJVVKV"), :as=> :meatballs
  match "/rak" => redirect("https://www.surveymonkey.com/s/GJZFJ2S"), :as => :rak
  match "/antologia" => redirect("/events/14")
  match "/capos" => redirect("/events/20")
  match "/radioafrica" => redirect("/events/24")
  match "/contraband" => redirect("/events/29")
  match "/onigilly" => redirect("/events/26")
  match "/HSC" => redirect("/events/30")
  match "/hsc" => redirect("/events/30")
  

  match 'events/:id/post_event' => 'events#post_event'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  skip_before_filter :authenticate_user!
  

  def howitworks
  end

  def teamandjobs
  end

  def index
  end

  def tos
  end

  def philosophy
  end

  def unsubscribe
  end

  def privacy
  end

  def raffle
    redirect_to "home/index"
  end

end

app/views/home/_sampleevent.html.haml
-if !event.upcoming?
  -if event.covers.present?
    =link_to (image_tag event.covers.first.image), event_path(event)
  -else
    =link_to image_tag("Food 26.jpg"), event_path(event)
  %a.caption{:href => event_path(event)}
    .caption-text
      %h4 #{event.title}
      %p #{event.host.profile.biz_name}
-else
  -if event.covers.present?
    =image_tag event.covers.first.image
  -else
    =image_tag("Food 26.jpg")
  %a.caption
    .caption-text
      %h4 #{event.title}
      %p Coming soon!

app/views/home/blog.html.erb
<h1>Home#blog</h1>
<p>Find me in app/views/home/blog.html.erb</p>

app/views/home/blog.html.haml
%body.container.staticpages
  .navbar.navbar-fixed-top
    = render "layouts/header"

  .hero-unit
    .copycontainer
      .darkbox.contactus
        .copy
          %h1 blog
          %h2 blahblahblah 
    #myCarousel.carousel.slide.contactus
      .carousel-inner
        .active.item 
          =image_tag "Food 12.jpg"
        .item
          =image_tag "Food 19.jpg"
        .item
          =image_tag "Food 24.jpg"
        .item
          =image_tag "Food 25.jpg"
      %a.carousel-control.left{"data-slide" => "prev", :href => "#myCarousel"} ‹
      %a.carousel-control.right{"data-slide" => "next", :href => "#myCarousel"} ›

app/views/home/contactus.haml
%body.container.home 
  .navbar.navbar-fixed-top
    = render "layouts/header"

%h1 Contact Us
%p blahblahblah

app/views/home/howitworks.haml
%body.container.home 
  .navbar.navbar-fixed-top
    = render "layouts/header"

%h1 How it works
%p blahblahblah

app/views/home/index.html.haml
=content_for :title, "Home"

.wow{'ng-controller'=>'HomeIndexCtrl', 'ng-init' => "appear='member'"}
  .home 
    .attention-getter
      #home-carousel.carousel.slide.hidden-phone
        .carousel-inner
          .active.item
            =image_tag "Contraband-2.jpg" #people
          .item
            =image_tag "Grindz.jpg" #food
          .item
            =image_tag "Onigilly.jpg" #menu
          .item
            =image_tag "Tava.jpg" #people
          .item
            =image_tag "Contraband-3.jpg" # bar closed
          .item
            =image_tag "Turtle-Tower.jpg" # food
          .item
            =image_tag "Capos-2.jpg" # old people
          .item
            =image_tag "Azalina.jpg" # food
          .item
            =image_tag "Contraband.jpg" #flip? people
        -#
          -all_events=Event.where("approved = ?", true)
          -i=0
          .carousel-inner
            -for event in all_events
              -if i==0
                .active.item
                  =render 'home/sampleevent', :event => event
              -else
                .item
                  =render 'home/sampleevent', :event => event
              -i=i+1
      %a.carousel-control.left.hidden-phone{"data-slide" => "prev", :href => "#home-carousel"} ‹
      %a.carousel-control.right.hidden-phone{"data-slide" => "next", :href => "#home-carousel"} ›
      .container
        .copy.row
          .span4.copy-content
            %h1 Insider access to top restaurants and bars
            %h2 Cooking classes, kitchen tours, special tastings &#8212 just for you
            .buttons
              -if user_signed_in? == false
                %a.btn.btn-warning.foodiesignup{:href => "#sign_up_foodie", :"data-toggle" =>"modal"} Sign Up
                
                %p Already a member? &nbsp <a href = "#sign_in" class = "sign-in-link" data-toggle = "modal"> Sign In </a>
              -if user_signed_in?
                %a.btn.btn-warning.view-events-button{:href => "/events"} browse experiences
                %p
                  = link_to "Sign Out", destroy_user_session_path, :method => :delete, :confirm => "Are you sure you want to sign out?", :class => 'sign-out-link'
            

    -#.section.how-it-works-section
      .container
        .row.section-header#hero-title{'ng-show' => "appear=='member'"}
          .span12#top.how-it-works
            .row
              .how-it-works
                %h2 What're Simmr experiences like?
            .step
              %h2 intimate
              .step-description
                %p Discover new businesses and get to know your favorites in groups of no more than 30
            .step
              %h2 hands-on
              .step-description
                %p Our experiences aren't like watching the Food Network...it's like being on the show
            .step
              %h2 delicious
              .step-description
                %p 'nuff said
          .span4.offset4#home-buttons
            -if user_signed_in?
              %a.btn.btn-warning{:href => "/events"} browse experiences
            -else
              %a.btn.btn-warning{:href => "#sign_up_foodie", :"data-toggle" =>"modal"} sign up

        .row.section-header#hero-title{'ng-show' => "appear=='host'"}
          .span12#top.how-it-works
            .step
              %h2 easy
              .step-description
                %p We take care of everything else so you can focus on doing what you do best -- delivering a great experience
            .step
              %h2 profitable
              .step-description
                %p We will work with you to make sure this is a sustainable way to build up your customer base
            .step
              %h2 just the start
              .step-description
                %p of much longer, deeper relationships with your customers. Simmr experiences both attract AND convert guests into loyal customers, with whom we want to help you keep in touch!
          .span4.offset4#home-buttons
            -if user_signed_in?
              %a.btn.btn-warning{:href => "/events"} get started
            -else
              %a.btn.btn-warning{:href => "#sign_up_foodie", :"data-toggle" =>"modal"} get started
      
      -#.row
        .offset4.span4#home-buttons
          %a.btn.btn-warning{'ng-click' => "appear='how'"} How It Works
          %a.btn.btn-warning{:href => "/home/philosophy"} Our Philosophy

    .events-index{'ng-controller' => 'EventIndexCtrl'}
      -all_events=Event.where(:approved => true)
      -upcoming_events = all_events.where(:upcoming=>true)
      -non_upcoming_events= all_events.where(:upcoming=>false)
      .events
        .container
          .row.section-header
            .span12.home-index-header
              %h1 Food Experiences in San Francisco
        .section.events-section
          .container
            .row.events-row-content
              .span2
              .span8.events-index-content
                -if current_user
                  -if current_user.chef == true
                    %p Look around and get some ideas!
                    - if all_events.length == 0
                      %p No experiences! How 'bout setting one up?
                  - if current_user.chef == false
                    %p Pick an experience to go to!
                    -if all_events.length == 0
                      %p No experiences! Sign up to stay up to date on future ones!
                -else
                  %p Pick an experience to go to!
                  -if all_events.length == 0
                    %p No experiences! Sign up to stay up to date on future ones!
                .events-index-navigation
                  %ul
                    %li
                      %a{:href => '#live'} Current
                    %li
                      %a{:href => '#new'} Preview Upcoming
                    %li
                      %a{:href => '#ongoing'} Popular and Recurring
        .container
          .row.section-header
            .span12.events-index-section-title-top#live
              %h1 Current Experiences
        .section.events-section
          .container
            .row.events-row-content
              .span2
              .span8.events-index-content
                -if current_user
                  -if current_user.chef == true
                    %p Current experiences are selling tickets now! Look around and see what's happenin'.
                  - if current_user.chef == false
                    %p Current experiences are selling tickets now! Buy yours today before they sell out.
                -else
                  %p Current experiences are selling tickets now! Buy yours today before they sell out.
        .container
          -potential_live_events=non_upcoming_events.dup
          -while potential_live_events.length > 1
            -event = potential_live_events.pop
            -if !event.happened?
              .row.events-row
                .span6.single-event
                  =render "events/singleevent", :event => event
                -event = potential_live_events.pop
                -if !event.happened?
                  .span6.single-event
                    =render "events/singleevent", :event => event
          -if potential_live_events.length == 1
            -event = potential_live_events.pop
            -if !event.happened?
              .row.events-row
                .span6.single-event
                  =render "events/singleevent", :event => event
                .span6

        .container
          .row.section-header
            .span12.events-index-section-title#new
              %h1 Preview Upcoming Experiences
        .section.events-section
          .container
            .row.events-row-content
              .span2
              .span8.events-index-content
                -if current_user
                  -if current_user.chef == true
                    %p Upcoming experiences are scheduled but not yet open for ticket sales. Follow (click on the heart) to get notified earlier than everybody else when ticket sales begin! 
                    -# what would you make this language, Neeharika?
                  - if current_user.chef == false
                    %p Upcoming experiences are scheduled but not yet open for ticket sales. Follow (click on the heart) to get notified earlier than everybody else when ticket sales begin! 
                -else
                  %p Upcoming experiences are scheduled but not yet open for ticket sales. Follow (click on the heart) to get notified earlier than everybody else when ticket sales begin! 
        .container
          -while upcoming_events.length > 1
            -event = upcoming_events.pop
            -if event.approved? && event.upcoming?
              .row.events-row
                .span6.single-event
                  =render "events/singleevent", :event => event
                -event = upcoming_events.pop
                -if event.approved? && event.upcoming?
                  .span6.single-event
                    =render "events/singleevent", :event => event
          -if upcoming_events.length == 1
            -event = upcoming_events.pop
            -if event.approved? && event.upcoming?
              .row.events-row
                .span6.single-event
                  =render "events/singleevent", :event => event
                .span6

        -potential_past_events = non_upcoming_events.dup
        .container
          .row.section-header
            .span12.events-index-section-title#ongoing
              %h1 Popular and Recurring Experiences
        .section.events-section
          .container
            .row.events-row-content
              .span2
              .span8.events-index-content
                -if current_user
                  -if current_user.chef == true
                    %p Recurring experiences have happened one or more times and have been really popular! Check out what's trending!
                  - if current_user.chef == false
                    %p Recurring experiences have happened one or more times and have been really popular! Put your name down for the next one -- the more names on the list, the sooner you can enjoy the experience.
                -else
                  %p Recurring experiences have happened one or more times and have been really popular! Put your name down for the next one -- the more names on the list, the sooner you can enjoy the experience.
        .container
          -while potential_past_events.length > 1
            -event = potential_past_events.pop
            -if event.happened?
              .row.events-row
                .span6.single-event
                  =render "events/singleevent", :event => event
                -event = potential_past_events.pop
                -if event.happened?
                  .span6.single-event
                    =render "events/singleevent", :event => event
          -if potential_past_events.length == 1
            -event = potential_past_events.pop
            -if event.happened?
              .row.events-row
                .span6.single-event
                  =render "events/singleevent", :event => event
                .span6

        .section.events-section
          .container
            .row.events-row-content
              .span12.events-index-content
                -if current_user
                  -if current_user.chef == true
                    %p Get a sense? <a href = "/events/new">Get your experience on Simmr</a> today!
                  -else
                    %p Don’t see your favorite business or a cool experience you want to see happen? <a href = "/campaigns/new">Suggest an experience</a> or <a href = "/campaigns">vote up a suggested experience</a> to make it happen on Simmr!
                -else
                  %p Don’t see your favorite business or a cool experience you want to see happen? <a href = "/campaigns/new">Suggest an experience</a> or <a href = "/campaigns">vote up a suggested experience</a> to make it happen on Simmr!
     
      %a.back-to-top{:href => '#top'}Back to Top



-# Uncomment the below to have the log in credential form rendered into this page
-# =render "shared/login"

-#  %form.navbar-search.pull-left.clearfix
-#    %input.search-query{:placeholder => "Find a Chef or Restaurant", :type => "text"}

app/views/home/indexYUI.html.haml
%body.container.home 
  .navbar.navbar-fixed-top 
    = render "layouts/header"

  .hero-unit
    .darkbox 
      .copy
        %h2 make your life more &nbsp <h1> delicious </h1>
        %h3 be the first to find out about exclusive food events
        %a.btn.btn-large.btn-warning{:href => "../home/howitworks", :tabindex => "-1"} how does it work?
    #myCarousel.carousel.slide
      .carousel-inner
        .active.item 
          =image_tag "Food 17.jpg"
        .item
          =image_tag "Food 18.jpg"
        .item
          =image_tag "Food 22.jpg"
        .item
          =image_tag "Food 23.jpg"
      %a.carousel-control.left{"data-slide" => "prev", :href => "#myCarousel"} ‹
      %a.carousel-control.right{"data-slide" => "next", :href => "#myCarousel"} ›
  .events
    %h1 Events in San Francisco
    %p Don't see your fave? <a href="#">Request</a> an event or see <a href="#">Request Campaigns</a>
    %ul.eventlisting
      %li.listing-card
        %a.listing-card-image{:href => "#"}
          =image_tag "event_stock_image.jpg"
        %table.listing-card-text
          %tr
            %td.listing-card-avatar
              =link_to image_tag("Favicon.png"), "#"
            %td.listing-card-event
              <a href="#">4 Course "Liberty Duck" Dinner with Chefs</a>
            %td.listing-card-price
              $120
          %tr.bottom
            %td
            %td.seatsleft
              5 seats left
              .progress.progress-warning
                .bar{:style => "width: 60%;"}
            %td.action
              .btn.btn-warning Go!
      %li.listing-card
        %a.listing-card-image{:href => "#"}
          =image_tag "event_stock_image.jpg"
        %table.listing-card-text
          %tr
            %td.listing-card-avatar
              =link_to image_tag("Favicon.png"), "#"
            %td.listing-card-event
              <a href="#">4 Course "Liberty Duck" Dinner with Chefs</a>
            %td.listing-card-price
              $120
          %tr.bottom
            %td
            %td.seatsleft
              5 seats left
              .progress.progress-warning
                .bar{:style => "width: 60%;"}
            %td.action
              .btn.btn-warning Go!
      %li.listing-card
        %a.listing-card-image{:href => "#"}
          =image_tag "event_stock_image.jpg"
        %table.listing-card-text
          %tr
            %td.listing-card-avatar
              =link_to image_tag("Favicon.png"), "#"
            %td.listing-card-event
              <a href="#">4 Course "Liberty Duck" Dinner with Chefs</a>
            %td.listing-card-price
              $120
          %tr.bottom
            %td
            %td.seatsleft
              5 seats left
              .progress.progress-warning
                .bar{:style => "width: 60%;"}
            %td.action
              .btn.btn-warning Go!
    .more.btn.btn-large.btn-warning More Events


-# Uncomment the below to have the log in credential form rendered into this page
-# =render "shared/login"

-#  %form.navbar-search.pull-left.clearfix
-#    %input.search-query{:placeholder => "Find a Chef or Restaurant", :type => "text"}

app/views/home/philosophy.html.haml
=content_for :title, "Philosophy"


.home{'ng-controller'=>'HomeIndexCtrl'}
  .philosophy-all
    #philosophy-carousel.carousel.slide.hidden-phone
      .carousel-inner
        .item.active
          =image_tag "TavaProfile2.jpg"
    -#
      %a.carousel-control.left.hidden-phone{"data-slide" => "prev", :href => "#home-carousel"} ‹
      %a.carousel-control.right.hidden-phone{"data-slide" => "next", :href => "#home-carousel"} ›
    .container
      .row
        .span6.philosophy
          %h3 a better way to eat out
 
          %p At Simmr, we want to help you get to know your favorite restaurants and discover new ones through behind the scenes experiences like cooking classes, kitchen tours, and special tastings. 

          %p We believe that upon having a memorable experience at a business and making friends with the people behind it, you are more likely to spread the word, and all of your subsequent visits will be different because you now know "the guy behind the counter."

          %p We do this all in a way that is profitable for the business. After all, running a restaurant, bar, or cafe isn't easy. The small business owners that create exceptional food and unforgettable experiences for us are passionate, hard-working, and often unthanked. Join us in helping them thrive.

          %p 
            %a.foodiesignup{:href => "#sign_up_foodie", :"data-toggle" =>"modal"}  Check out experiences at the businesses you love.

          %p
            %a.bizsignup{:href => "#sign_up_business", :"data-toggle" =>"modal"} Or, if you're a business owner, start getting more loyal customers.

app/views/home/raffle.html.haml
-#<a id="rc-cf429a0" class="rafl" href="http://www.rafflecopter.com/rafl/display/cf429a0/" rel="nofollow">a Rafflecopter giveaway</a>
-#<script src="//d12vno17mo87cx.cloudfront.net/embed/rafl/cptr.js"></script>

app/views/home/teamandjobs.haml
%body.container.home 
  .navbar.navbar-fixed-top
    = render "layouts/header"

%h1 Team and Jobs
%p blahblahblah

app/views/home/teamandjobs.html.haml
=content_for :title, "Team & Jobs"


.container.team-jobs
  .row
    .span12
      %h1 Let's taco 'bout us
      %h3 Join us in building a platform that revolutionizes "local"
  .row
    .span10.offset1.wendyandnee
      =image_tag "wendyandneeharika.png"
  .row
    .span12
      %h1 At Simmr we
  .row
    .company-culture
      .span3
        .step
          %h3.point-heading Work Hard <br>Move Fast
          .step-description
            %p We're nimble, passionate, and determined. There is no shortage of responsibility and we want you to have a voice in everything we do.
      .span3
        .step
          %h3.point-heading#have-fun Have Fun
          .step-description
            %p It's not a job if you're having fun :)
      .span3
        .step
          %h3.point-heading#stay-humble Stay Humble
          .step-description
            %p We put aside egos for the sake of learning.
      .span3
        .step
          %h3.point-heading#difference Make a Difference
          .step-description
            %p We're fundamentally changing the relationship between a customer and a small business. These businesses make up the fabric of our lives and economies.
  .row
    .span12 
      %h1 We're always looking for great people
      %h2 If you're interested, <a href="mailto:hello@simmr.co">drop us a line!</a>

app/views/home/unsubscribe.html.haml
=content_for :title, "Unsubscribe"


.container.unsubscribe
  .row
    .span10.offset1
      %h1 Is this really the end?
      %h2 Was it us? Did we change? 
      %a.email{:href => "mailto:hello@simmr.co?Subject=Sorry, it's over&body=I unsubscribed because..."} Tell us how we could've done better...
      %h3 Give us a second chance?
      .fb-like{"data-href" => "http://www.facebook.com/simmrco", "data-layout" => "button_count", "data-show-faces" => "true", "data-width" => "100"}
      %a.twitter-follow-button{"data-show-count" => "false", :href => "https://twitter.com/simmrco"} 
      :javascript
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');